# Generated by Django 3.0.5 on 2020-05-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerUser',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('persona_id', models.CharField(max_length=40)),
                ('persona_government_id_url', models.CharField(max_length=40)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
