# Generated by Django 3.0.5 on 2020-05-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vogro_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('address_name', models.CharField(max_length=30)),
                ('reason', models.CharField(max_length=50)),
            ],
        ),
    ]
