# Generated by Django 3.0.5 on 2020-05-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vogro_api', '0003_auto_20200505_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='address_name',
            field=models.CharField(max_length=100),
        ),
    ]
