# Generated by Django 3.0.5 on 2020-05-06 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vogro_api', '0004_auto_20200505_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_location', models.TextField()),
                ('description', models.CharField(max_length=50)),
                ('task_type', models.CharField(max_length=30)),
                ('client_name', models.CharField(max_length=30)),
                ('earliest_preferred_time', models.DateTimeField()),
                ('latest_preferred_time', models.DateTimeField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vogro_api.ClientUser')),
            ],
        ),
    ]
