# Generated by Django 3.0.5 on 2020-05-06 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vogro_api', '0005_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='client_id',
        ),
    ]
