# Generated by Django 3.0.5 on 2020-05-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vogro_api', '0011_auto_20200510_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtask',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='matchedtask',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='unmatchedtask',
            name='description',
            field=models.TextField(),
        ),
    ]
