# Generated by Django 3.0.5 on 2020-05-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vogro_api', '0012_auto_20200510_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeruser',
            name='phone_number',
            field=models.CharField(max_length=25),
        ),
    ]
