# Generated by Django 3.0.5 on 2020-05-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vogro_api', '0015_clientuser_completedtask_matchedtask_task_unmatchedtask_volunteeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='estimated_time',
            field=models.CharField(default='30 min', max_length=20),
        ),
        migrations.AddField(
            model_name='matchedtask',
            name='estimated_time',
            field=models.CharField(default='30 min', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.CharField(default='30 min', max_length=20),
        ),
        migrations.AddField(
            model_name='unmatchedtask',
            name='estimated_time',
            field=models.CharField(default='30 min', max_length=20),
        ),
    ]
