# Generated by Django 3.0.5 on 2020-05-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vogro_api', '0016_auto_20200517_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientUser',
        ),
        migrations.RemoveField(
            model_name='completedtask',
            name='volunteer_id',
        ),
        migrations.RemoveField(
            model_name='matchedtask',
            name='volunteer_id',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='UnMatchedTask',
        ),
        migrations.DeleteModel(
            name='CompletedTask',
        ),
        migrations.DeleteModel(
            name='MatchedTask',
        ),
        migrations.DeleteModel(
            name='VolunteerUser',
        ),
    ]
